/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "isr_UART_RX.h"
#include "Pin_N_R_aliases.h"
#include "Pin_N_R.h"
#include "Pin_N_Y_aliases.h"
#include "Pin_N_Y.h"
#include "Pin_N_G_aliases.h"
#include "Pin_N_G.h"
#include "Pin_E_CW_aliases.h"
#include "Pin_E_CW.h"
#include "Pin_CWEW_aliases.h"
#include "Pin_CWEW.h"
#include "isr_CWEW.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

